name: Daily Update

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '*.md'
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Keep scheduled workflow activity
      uses: WaterLemons2k/scheduled-workflow-activity-action@v1

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 0

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download resources
      run: |
        mkdir -p ./publish/geosite
        mkdir -p ./publish/geoip
        mkdir -p work
        cd work || exit 1
        curl -s -O https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geosite.dat
        curl -s -O https://raw.githubusercontent.com/lingeringsound/10007_auto/main/configure/保留奖励.prop
        # curl -s -O https://raw.githubusercontent.com/lingeringsound/10007_auto/main/reward

    - name: Download mihomo
      run: |
        wget -q -O ./mihomo.gz $(curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | grep -E -o 'https://[^"]*/mihomo-linux-amd64-v[0-9.]+\.gz')
        gzip -d mihomo.gz
        chmod +x mihomo
    
    - name: Download sing-box
      run: |
        wget -q -O ./sing-box.tar.gz $(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | grep -E -o 'https://[^"]*/sing-box-[0-9.]+-linux-amd64\.tar\.gz')
        tar -zxvf sing-box.tar.gz --strip-components=1 --wildcards '*/sing-box'
        chmod +x sing-box

    - name: Download yq
      run: |
        wget -q -O ./yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        chmod +x yq

    - name: Download jq
      run: |
        wget -q -O ./jq https://github.com/jqlang/jq/releases/latest/download/jq-linux-amd64
        chmod +x jq

    - name: Download geo
      run: |
        wget -q -O ./geo https://github.com/MetaCubeX/geo/releases/latest/download/geo-linux-amd64
        chmod +x geo

    - name: Build mrs
      run: |
        cd work || exit 1

        ../geo unpack site ./geosite.dat -d . -c category-dev
        cat category-dev | grep -Ev "@ads|@cn" | perl -ne '/^((domain|full|regex):[^:]+)(\n$|:@.+)/ && print "$1\n"' | sed 's/^domain:/DOMAIN-SUFFIX,/I' | sed 's/^full:/DOMAIN,/I' | sed 's/^regex:/DOMAIN-REGEX,/I' > ../publish/geosite/category-dev-!cn.list

        grep -v "^#" "保留奖励.prop" > ../publish/geosite/reward.list

        # grep '^0\.0\.0\.0 ' reward | awk '{print $2}' | sed 's/\.$//' > ads.txt
        # grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$' ads.txt > ip.txt
        # sed 's/$/\/32/' ip.txt > ../publish/geoip/ads.list
        # grep -E -v '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$' ads.txt > ../publish/geosite/ads.list

        ../mihomo convert-ruleset domain text ../publish/geosite/reward.list ../publish/geosite/reward.mrs
        # ../mihomo convert-ruleset domain text ../publish/geosite/ads.list ../publish/geosite/ads.mrs
        # ../mihomo convert-ruleset ipcidr text ../publish/geoip/ads.list ../publish/geoip/ads.mrs

    - name: Build srs
      run: |
        cd work || exit 1

        cat ../publish/geosite/reward.list | ../jq -R -s '
          split("\n") | 
          map(select(length > 0)) | 
          {
            version: 2,
            rules: [
              {
                domain: .
              }
            ]
          }' > ../publish/geosite/reward.json

        ../sing-box rule-set compile ../publish/geosite/reward.json

    - name: Commit and push
      run: |
        cd publish || exit 1
        git init
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git checkout -b release
        git add .
        git commit -m "Auto-update"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin release

    - name: Purge jsdelivr CDN
      run: |
        cd publish || exit 1
        find . -type f \( -name "*.mrs" -o -name "*.list" \) -print0 | while IFS= read -r -d '' path; do
            file_path="${path#./}"
            echo "Purging $file_path"
            curl -s -I "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/$file_path"
        done

    env:
      TZ: Asia/Shanghai
